
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet 



export ZSH="$HOME/.oh-my-zsh"
export PATH="$HOME/.local/bin:$PATH"

ZSH_THEME="powerlevel10k/powerlevel10k"


source $ZSH/oh-my-zsh.sh

# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
alias ls="eza -l"
alias i="yay -S"
alias s="yay -Ss"
alias rr="yay -Rns"
alias p="sudo pacman -S"
alias r="sudo pacman -Rns"
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export PATH="$HOME/bin:$PATH"

# Run Fastfetch on terminal startup
fastfetch


